---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kehystys/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp nav.js $DEPLOYPATH
    - /bin/cp dark.js $DEPLOYPATH
    - /bin/cp *.png $DEPLOYPATH
    - /bin/cp browserconfig.xml $DEPLOYPATH
    - /bin/cp favicon.ico favicon.svg $DEPLOYPATH
    - /bin/cp -R fonts images css $DEPLOYPATH
    - /bin/cp site.webmanifest $DEPLOYPATH